Reading trace from rewritten_trace_1
Replay enabled
Exit Replay with code  3 The program panicked unexpectedly
panic: send on closed channel

goroutine 39 [running]:
canonicalTests/tests.n09.func2()
	/home/mario/Desktop/thesis/ADVOCATE/examples/canonicalTests/tests/n09_test.go:30 +0x25
created by canonicalTests/tests.n09 in goroutine 18
	/home/mario/Desktop/thesis/ADVOCATE/examples/canonicalTests/tests/n09_test.go:28 +0xdc
FAIL	canonicalTests/tests	0.348s
FAIL
