Reading trace from rewritten_trace_1
Replay enabled
Exit Replay with code  3 The program panicked unexpectedly
panic: send on closed channel

goroutine 51 [running]:
canonicalTests/tests.n10.func2()
	/home/mario/Desktop/thesis/ADVOCATE/examples/canonicalTests/tests/n10_test.go:29 +0x1c
created by canonicalTests/tests.n10 in goroutine 18
	/home/mario/Desktop/thesis/ADVOCATE/examples/canonicalTests/tests/n10_test.go:27 +0xa5
FAIL	canonicalTests/tests	0.284s
FAIL
